src/menus/urls.py
from django.conf.urls import url

from .views import (
    ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^create/$',  ItemCreateView.as_view(), name='create'),
    #url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'$', ItemListView.as_view(), name='list'),
]

src/picky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


from django.contrib.auth.views import LoginView, LogoutView

from menus.views import HomeView, AllUserRecentItemListView
from profiles.views import ProfileFollowToggle, RegisterView, activate_user_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^recent/$', AllUserRecentItemListView.as_view(), name='recent'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

src/menus/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse

from restaurants.models import RestaurantLocation

class Item(models.Model):
    # associations
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    restaurant      = models.ForeignKey(RestaurantLocation)
    # item stuff
    name            = models.CharField(max_length=120)
    contents        = models.TextField(help_text='Separate each item by comma')
    excludes        = models.TextField(blank=True, null=True, help_text='Separate each item by comma')
    public          = models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)
    updated         = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self): #get_absolute_url
        #return f"/restaurants/{self.slug}"
        return reverse('menus:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_contents(self):
        return self.contents.split(",")

    def get_excludes(self):
        return self.excludes.split(",")

src/menus/forms.py
from django import forms

from restaurants.models import RestaurantLocation

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'restaurant',
            'name',
            'contents',
            'excludes',
            'public'
        ]
    def __init__(self, user=None, *args, **kwargs):
        #print(kwargs.pop('user'))
        print(user)
        print(kwargs)
        super(ItemForm, self).__init__(*args,**kwargs)
        self.fields['restaurant'].queryset = RestaurantLocation.objects.filter(owner=user)# .exclude(item__isnull=False)

src/menus/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, DetailView, View
# Create your views here.
from menus.models import Item
from restaurants.models import RestaurantLocation

from .forms import RegisterForm
from .models import Profile
User = get_user_model()


def activate_user_view(request, code=None, *args, **kwargs):
    if code:
        qs = Profile.objects.filter(activation_key=code)
        if qs.exists() and qs.count() == 1:
            profile = qs.first()
            if not profile.activated:
                user_ = profile.user
                user_.is_active = True
                user_.save()
                profile.activated=True
                profile.activation_key=None
                profile.save()
                return redirect("/login")
    return redirect("/login")



class RegisterView(SuccessMessageMixin, CreateView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = '/'
    success_message = "Your account was created successfully. Please check your email."

    def dispatch(self, *args, **kwargs):
        # if self.request.user.is_authenticated():
        #     return redirect("/logout")
        return super(RegisterView, self).dispatch(*args, **kwargs)



class ProfileFollowToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        username_to_toggle = request.POST.get("username")
        profile_, is_following = Profile.objects.toggle_follow(request.user, username_to_toggle)
        return redirect(f"/u/{profile_.user.username}/")



class RandomProfileDetailView(DetailView):
    template_name = 'profiles/user.html'

    def get_object(self):
        return User.objects.filter(is_active=True, item__isnull=False).order_by("?").first() #/ gives a random item.

    def get_context_data(self, *args, **kwargs):
        context = super(RandomProfileDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']
        is_following = False
        if self.request.user.is_authenticated():
            if user.profile in self.request.user.is_following.all():
                is_following = True
        context['is_following'] = is_following
        query = self.request.GET.get('q')
        items_exists = Item.objects.filter(user=user).exists()
        qs = RestaurantLocation.objects.filter(owner=user).search(query)
        if items_exists and qs.exists():
            context['locations'] = qs
        return context


class ProfileDetailView(DetailView):
    template_name = 'profiles/user.html'

    def get_object(self):
        username = self.kwargs.get("username")
        if username is None:
            raise Http404
        return get_object_or_404(User, username__iexact=username, is_active=True)

    def get_context_data(self, *args, **kwargs):
        context = super(ProfileDetailView, self).get_context_data(*args, **kwargs)
        user = context['user']
        is_following = False
        if self.request.user.is_authenticated():
            if user.profile in self.request.user.is_following.all():
                is_following = True
        context['is_following'] = is_following
        query = self.request.GET.get('q')
        items_exists = Item.objects.filter(user=user).exists()
        qs = RestaurantLocation.objects.filter(owner=user).search(query)
        if items_exists and qs.exists():
            context['locations'] = qs
        return context

src/menus/templates/menus/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.name }} | Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ form.instance.name }}</h1>
<p>Location: {{ form.instance.restaurant.name }}</p>
{% if form.instance.contents %}
Contents
<ul>    
    {% for item in form.instance.get_contents %}
    <li>{{ item }}</li>
    {% endfor %}

</ul>
{% endif %}

 {% if form.instance.excludes %}
Excludes
<ul>    
    {% for item in form.instance.get_excludes %}
    <li>{{ item }}</li>
    {% endfor %}

</ul>
{% endif %}

<hr/>
<h3>Make changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}

</div>
</div>
{% endblock %}

src/menus/templates/menus/home-feed.html
{% extends 'base.html' %}

{% block content %}

    <div class='row'>
    <div class='col-sm-6 text-center col-sm-offset-3'>
         <h1>User Following Feed</h1>


{% for obj in object_list %}


        <div class='thumbnail'> 
            <h3><a href='{% url "profiles:detail" username=obj.user.username %}'>{{ obj.user.username }}</a></h3>
            <h4>{{ obj.name }}</h4>
            <p><a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.title }}'>{{ obj.restaurant.title }}</a>| <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.location }}'>{{ obj.restaurant.location }}</a> | <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ obj.restaurant.category }}'>{{ obj.restaurant.category }}</a></p>
            <p>
            <b>{{ obj.name }}:</b> with
             {% for ing in obj.get_contents %}
                <a href='{% url "profiles:detail" username=obj.user.username %}?q={{ ing}}'>{{ ing}}</a>
            {% endfor %}
            </p>
        </div>



{% endfor %}

    </div>
    </div>

{% endblock %}

src/menus/templates/menus/item_detail.html
{% extends "base.html" %}

{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ object.name }}</h1>
<p>Location: {{ object.restaurant.name }}</p>
{% if object.contents %}
Contents
<ul>    
    {% for item in object.get_contents %}
    <li>{{ item }}</li>
    {% endfor %}

</ul>
{% endif %}

 {% if object.excludes %}
Excludes
<ul>    
    {% for item in object.get_excludes %}
    <li>{{ item }}</li>
    {% endfor %}

</ul>
</div>
</div>
{% endif %}


{% endblock %}

src/menus/templates/menus/item_list.html
{% extends "base.html" %}

{% block head_title %}Menu Items | {{ block.super}}{% endblock head_title %}

{% block content %}
<div class='row'>
<div class='col-sm-6 col-sm-offset-3'>
<h1>Menu Items <small><a href='{% url "menus:create" %}'>Add</a></small></h1>

<ul>
{% for obj in object_list %}
    <li><a href='{{ obj.get_absolute_url }}'>{{ obj.name }}</a><br/>
        {% if obj.contents %}
        Contents
        <ul>    
            {% for item in obj.get_contents %}
            <li>{{ item }}</li>
            {% endfor %}

        </ul>
        {% endif %}

         {% if obj.excludes %}
        Excludes
        <ul>    
            {% for item in obj.get_excludes %}
            <li>{{ item }}</li>
            {% endfor %}

        </ul>
        {% endif %}


    </li>
    {% empty %}
    <li><a href='{% url "menus:create" %}'>Add Menu Item</a></li>
</ul>
</div>
</div>
{% endfor %}
</ul>
{% endblock %}